# .github/workflows/flaticon-batch.yml
name: Fetch Flaticon Icons (Batch)

on:
  workflow_dispatch:
    inputs:
      format:
        description: "Download format"
        required: true
        default: "png"
        type: choice
        options: [png, svg]
      size:
        description: "PNG size (ignored for SVG)"
        required: true
        default: "128"
        type: string
      out:
        description: "Output directory"
        required: true
        default: "icons"
        type: string

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Fetch icons
        env:
          FLATICON_API_KEY: ${{ secrets.FLATICON_API_KEY }}
        run: |
          python scripts/fetch_flaticon_batch.py \
            --file queries.txt \
            --format "${{ github.event.inputs.format }}" \
            --size "${{ github.event.inputs.size }}" \
            --out "${{ github.event.inputs.out }}"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: flaticon-icons
          path: ${{ github.event.inputs.out }}
